repos:
  # --- Ruff: Linter & Formatter ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # --- Black: Code formatter ---
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3

  # --- isort: Import sorter ---
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        additional_dependencies: [tomli]  # pour compatibilité Windows/pyproject

  # --- mypy: Static type checker ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-redis, types-Pillow]

default_language_version:
  python: python3
