name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install project and dev tools
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .
          python -m spacy download en_core_web_sm

      - name: Lint (ruff)
        run: ruff check src/color_sentiment_extractor

      - name: Type check (mypy)
        run: mypy src/color_sentiment_extractor

      - name: Run tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=color_sentiment_extractor \
                 --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
